# Generated by Django 4.0.3 on 2023-03-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_userbankaccount_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balence_after_transaction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'deposite'), (2, 'withdrawal'), (3, 'transfer')])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userbankaccount')),
            ],
        ),
    ]
