# Generated by Django 4.0.3 on 2023-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_to',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
