# Generated by Django 4.0.3 on 2023-03-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankusers_alter_useraddress_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankusers',
            old_name='username',
            new_name='bankuser',
        ),
    ]
