# Generated by Django 4.0.3 on 2023-03-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_username_bankusers_bankuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounttype',
            name='name',
            field=models.CharField(help_text='Enter Account Type Current/Saving', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='accounts.bankusers'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.bankaccounttype'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.bankusers'),
        ),
    ]
