# Generated by Django 4.0.3 on 2023-03-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bankaccounttype_name_alter_useraddress_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.CharField(help_text='Enter Account Type Current/Saving', max_length=100),
        ),
    ]
