# Generated by Django 4.0.3 on 2023-03-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useraddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='user',
            new_name='bankuser',
        ),
    ]
